base:
  website: 'http://192.168.5.8:7777'   # 域名 指向到该服务及其端口
  port: '7779'  # 服务启动端口
  length: 8     # 短链接秘钥生成长度
  cacheTime: 60 # 内存缓存时间，分钟

redis:
  addr: '192.168.5.8'   # 地址
  port: '6379'      # 端口号
  pwd:  'shatang'   # 密码
